### ISSUE TITLE
vRA project permissions of group type fails

### ISSUE THREAD

**Issue by VickyWinner** [vmware/terraform-provider-vra#371] opened 2021-08-15 21:12 UTC
**vRA version**
The vRA Cloud / 8.x version where is issue is found.
vRealize Automation 8.4.1.16947 (18054500)

**Terraform version**
Terraform v1.0.4

**terraform-provider-vra plugin version**
+ provider registry.terraform.io/vmware/vra v0.3.8

**Describe the bug**
This issue is referring to the issue raised [here](https://github.com/vmware/terraform-provider-vra/issues/336) to address the project permissions.  After granting administrator/member/vierwer permissions to the project for the group email, there is still no access to the members of that group.  I am able to see the usertype as group listed in the service broker-->projects--users.

**To Reproduce**
Just follow the example and try to grant access to group type AD user following the format. group@domain.com.

**Expected behavior**
Should be able to sync from vIDM and grant appropriate permissions.

**Screenshots**
attached below

**Logs**
Can attach logs if required.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

![image](https://user-images.githubusercontent.com/33285331/129492995-b0a6e030-c3f5-4f40-bea5-ab77beaeada8.png)

**Comment by dondon3345678** [comment] 2021-08-23 21:11
Hi,

Could you specify 
1. The role of the user configured in vIDM
2. The role of the group configured in the terraform config file (administrator_roles or member_roles or view_roles)
3. How do you verify if a user have the accessibility to the project created by terraform provider?

Thanks,
Daniel

**Comment by VickyWinner** [comment] 2021-08-23 22:34
I tried all the combinations available.  Not sure what exactly you are looking for.  However, here are the details:
The role of the user configured in vIDM

> Organization member with  Service Broker User,  Orchestrator Viewer, Cloud Assembly Viewer.

The role of the group configured in the terraform config file (administrator_roles or member_roles or view_roles)

> I have groups having all the available roles defined.  In all combinations.

How do you verify if a user have the accessibility to the project created by terraform provider?

> By logging into using the user member of the group.

**Comment by dondon3345678** [comment] 2021-08-30 18:36
Hi,

I tried to reproduce the issue by assigning a user of the group (eg: group@example.com) with the service roles

<img width="1273" alt="Service roles of the user of the group" src="https://user-images.githubusercontent.com/6981726/131387152-e2c1e6a6-9156-4b42-8d23-84de9a30be3a.png">

Then I create a project through terraform configured with group permission

```
resource "vra_project" "vmc-project" {
  name        = "test proj"
  description = "created via vra terraform provider"


  administrator_roles {
    email = "group@example.com"
    type = "group"
  }
}
```
Finally, I can login can see the project in vRA.

<img width="1601" alt="Login with the user of the group" src="https://user-images.githubusercontent.com/6981726/131387147-ad2afcb8-c2f0-45b8-9656-a4010bf73206.png">

Please let me know if I am reproducing the issue in the way you expect. 

Thanks,
Daniel

**Comment by VickyWinner** [comment] 2021-08-30 22:42
@dondon3345678 I am assigning the service role to the group email not the user of the group.  I can select the vIDM group name from the drop down and that is how I am assigning the roles to the group email directly.  After granting permission to the group email, I will login to UI using the user (who is member of that group) and verify.

**Comment by dondon3345678** [comment] 2021-08-31 19:03
Hi,

I tried to assign service role to the _group email_ directly in "Identity & Access Management" -> "Enterprise Groups"
Fritz is admin.

<img width="1601" alt="Assign_service_role_to_group" src="https://user-images.githubusercontent.com/6981726/131560484-d53636cd-a0ed-4afb-a56c-fba8ebf251d8.png">

Then service roles of every user in the configured group are updated automatically. So that I login with a user in the group through UI and I can see the project.
Tony is the user in the group.


<img width="1602" alt="User_of_the_group_access_proj" src="https://user-images.githubusercontent.com/6981726/131560775-b05af148-df95-49ee-94db-652c269598ba.png">

**Comment by githubusersaranya** [comment] 2021-09-02 17:58
@dondon3345678 Actually you are right when we assign particular role to user or group, we are doing good with manual UI changes , that specific user or group members able to login and have permissions to that project whether as real issue comes when we add Group through terraform code , it is actually adding to that project , but user inside that group are unable to login and consume vRA8 console project access

**Comment by VickyWinner** [comment] 2021-09-07 12:45
@dondon3345678, did you looked at what @githubusersaranya mentioned?  Are you looking for anything more from my end?

**Comment by dondon3345678** [comment] 2021-09-08 17:57
Hi, 

Did you manually assign the service role to the user of the group in "Identity & Access Management"? The project IAAS api doesn't assign service role to the user/group automatically when they are added to the project.

**Comment by VickyWinner** [comment] 2021-09-08 18:00
Agree @dondon3345678.  I had to add the service and organization role to the group (not user) usng IAM.

**Comment by dondon3345678** [comment] 2021-09-13 17:39
@VickyWinner could you confirm that after adding user to the group with IAM, the user can login and has the permission of the project when you add role to the group? If yes, then we can close this bug.

**Comment by VickyWinner** [comment] 2021-09-13 22:21
@dondon3345678 ,  I thought I made it clear earlier.  here are the steps I followed.  
Sync FIM group created in Active Directory (Integrated Windows Authentication) using vIDM
grant Organization and Service roles to the FIM/AD group
create project using terraform and grant access (member/viewer/administrator) to the FIM group using `group` per code above.
Now when I login using the AD Id which is member of the FIM group, it fails to login.

does this makes sense?

**Comment by dondon3345678** [comment] 2021-09-14 04:46
Hi @VickyWinner 
Let me follow your steps to reproduce
1. Sync FIM group created in Active Directory (Integrated Windows Authentication) using vIDM
<img width="1597" alt="Group created in AD" src="https://user-images.githubusercontent.com/6981726/133195991-5d45919c-14a0-4d13-bce7-1c141943c079.png">
2. grant Organization and Service roles to the FIM/AD group
<img width="1280" alt="Grant role to the group only" src="https://user-images.githubusercontent.com/6981726/133196123-756f8877-86b6-4105-87a5-967a3efa5547.png">
User of the group was granted the same permission
<img width="1273" alt="User get the same permission" src="https://user-images.githubusercontent.com/6981726/133196129-5d40bbfc-db00-4214-ac55-93141731a3a8.png">
3. create project using terraform and grant access (member/viewer/administrator) to the FIM group using group per code above.
<img width="786" alt="Create project in terraform and grant project admin role to GROUP" src="https://user-images.githubusercontent.com/6981726/133196294-21aed286-e339-45e0-9e6c-e1e958d82e55.png">
4. I login using the AD Id which is member of the FIM group
<img width="1588" alt="Login using Susan, member of the group" src="https://user-images.githubusercontent.com/6981726/133196401-e3d1ee48-68b4-496d-80df-366aa3fc4679.png">

Please let me know if I did any step wrong.
Daniel

**Comment by VickyWinner** [comment] 2021-09-14 16:08
@dondon3345678,  in step 3, any reason you granted org/services roles to FIM/AD group and also the user of the group?  I didn't do anything in vIDM or vRA project with the user.  all steps in vIDM/vRA IAM were related to to FIM/AD group only.  When  I login, I login using the user, which is part of the that group.

**Comment by dondon3345678** [comment] 2021-09-20 19:12
You have to grant org/service role to the group so that all users of it will be granted the same permissions to access vRA. In step3, the user permission is granted **automatically**. This is necessary, otherwise the user won't be able to login even though its group has project admin/viewer/user permission.

**Comment by VickyWinner** [comment] 2021-09-20 20:44
![image](https://user-images.githubusercontent.com/33285331/134072928-1790bed4-beed-4526-b4cf-f2afbdf3b968.png)

@dondon3345678 I did grant org/service role(s) to the group.  After that only I am using terraform to grant access using administrator_roles/member_roles/viewer_roles.  In the above steps, any reason you granting access (org/service role) to the user of the group instead of the group itself?

**Comment by dondon3345678** [comment] 2021-09-21 06:19
@VickyWinner I didn't grant permission to the user **manually**, this is done **automatically** when you grant the permission to the group of this user. So that the user can access vRA services(service broker, Orch, Cloud Assembly).

**Comment by VickyWinner** [comment] 2021-11-01 17:45
@dondon3345678 if your test is working correctly, then it could be something wrong in my code.  Not sure.  So, here is how I am adding multiple FIM groups.  There might be something fishy in my code as I can see that when I follow below code, I see `fimgroup1 | domain.com` under users tab in projects whereas if I am adding a FIM group from GUI, I would see `fimgroup1@domain.com | domain.com`.

```hcl
variable "administrators" {
  type        = list(string)
  default     = [
    "fimgroup1@domain.com",
    "fimgroup2@domain.com"
  ]
}

locals {
  administrators = toset(var.administrators)
}

resource "vra_project" "this" {
.
.
.
  dynamic "administrator_roles" {
    for_each = local.administrators
    content {
      email = administrator_roles
      type  = "group"
    }
  }
}
```

**Comment by VickyWinner** [comment] 2021-11-01 22:26
@dondon3345678 I did try with below code by adding @domain.com additional to the FIM group email argument.  It works this way.

```hcl
  member_roles {
    email = "fimgroup1@domain.com@domain.com"
    type  = "group"
  }
```

**Comment by dondon3345678** [comment] 2021-11-08 20:24
Hi @VickyWinner 
Happy to hear that it's working now, let me close this issue.

**Closed by dondon3345678** 2021-11-08 20:24 UTC
Labels: bug

**Comment by VickyWinner** [comment] 2021-11-10 14:03
It is working through a workaround.  Does it mean, that is how it should be provided?  Was it that way you tested too by adding FIMgroup1@domain.com@domain.com like doubling the domain name?

**Comment by dondon3345678** [comment] 2021-12-09 16:58
Since you are seeing `fimgroup1@domain.com | domain.com` in UI, that means you need to add this group with double domain name format. I am not sure why the UI is showing this strange format, I saw this double domain name format even in the example I provided above.
