### ISSUE TITLE
State is not refreshed correctly when vRA fails to deploy

### ISSUE THREAD

**Issue by jmrchaves88** [vmware/terraform-provider-vra#153] opened 2020-01-27 17:47 UTC
After a failed deployment state is not refreshed resulting in:

Error: The resource cannot be found

**Comment by jmrchaves88** [comment] 2020-01-27 17:49
Workaround so far is to do a state rm on the deployment

**Comment by dmettem** [comment] 2020-04-09 20:56
@jmrchaves88 - Can you provide information for the following:
1. Is the deployment requested with blueprint id or catalog item id?
2. What's the reason for the failure?
3. Can you still reproduce? If so, please provide the logs.

**Comment by dmettem** [comment] 2020-04-25 01:41
@jmrchaves88 This is fixed in [v0.1.9](https://github.com/vmware/terraform-provider-vra/releases/tag/v0.1.9).

Deployment id is persisted in state file during create, so that even if the deployment fails or times out, the deployment resource is still created in the state file and refresh works.

In case the provider times out before the deployment request completes i.e
successful or failed, refresh will pull the latest state of deployment.
For in-place updates of such deployment resources that timed out during
create should be `untainted` first.

Please let me know how it works for you.

**Comment by jmrchaves88** [comment] 2020-04-25 01:44
Sorry for not replying to this earlier. Thanks for letting me know I’ll test and report back.

Thanks again!

**Comment by dmettem** [comment] 2020-05-04 20:45
@jmrchaves88 Do you have an update from your test? I'm closing the issue for now. Please feel free to reopen if you still see the issue.

**Closed by dmettem** 2020-05-04 20:45 UTC
Labels: bug, fixed
