### ISSUE TITLE
When adding a cloud account, the region is labeled as the externalRegionId rather than the vSphere datacenter name

### ISSUE THREAD

**Issue by ricardoconzatti** [vmware/terraform-provider-vra#511] opened 2023-11-28 22:05 UTC
### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [x] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### vRA Version
8.13 

### Terraform Version
1.6.4

### vRA Terraform Provider Version
0.8.3

### Affected Resource(s)
vra_cloud_account_vsphere

### Terraform Configuration Files
```
data "vra_region_enumeration_vsphere" "this" {
  hostname                            = "vcenter-02.caverna.local"
  username                            = "svc.vra@caverna.local"
  password                            = ""
  accept_self_signed_cert  = true
}

resource "vra_cloud_account_vsphere" "this" {
  name            = "Caverna vCenter 02"
  description  = ""
  hostname    = "vcenter-02.caverna.local"
  username    = "svc.vra@caverna.local"
  password    = ""
  
  regions                                = data.vra_region_enumeration_vsphere.this.regions
  accept_self_signed_cert  = true
}
```

### Expected Behavior
Create a new cloud account and allow provisioning to all existing vSphere datacenters (regions). The region name should be the datacenter name (in my example, it should be "Caverna Cloud 02").

### Actual Behavior
The new cloud account was created with no errors, but the vSphere regions were configured by ID (externalRegionId). When I edit the new cloud account and save that without any change, the region name changed from externalRegionId to Name (vSphere datacenter name).

### Steps to Reproduce
Just run a terraform apply using the code above and check the column Account / Region in Compute (Assembler > Infrastructure > Resources > Compute).

### Screenshots
![Screenshot 2023-11-28 at 18 32 45](https://github.com/vmware/terraform-provider-vra/assets/22546033/845c0da3-e8ff-4183-a03d-e4dd60a674c3)

![Screenshot 2023-11-28 at 18 33 14](https://github.com/vmware/terraform-provider-vra/assets/22546033/c5a8568a-6adf-478d-84fe-de4984ca124f)

![Screenshot 2023-11-28 at 18 33 36](https://github.com/vmware/terraform-provider-vra/assets/22546033/58b3b951-7e50-408d-b060-32bea87de760)

### Debug Output
N/A

### Panic Output
N/A

### Important Factoids
N/A

### References
N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BerryR-RBA** [comment] 2024-02-15 23:41
Hi @ricardoconzatti, is this a duplicate of #472?

**Comment by ricardoconzatti** [comment] 2024-02-16 00:11
> Hi @ricardoconzatti, is this a duplicate of #472?

Heey @BerryR-RBA. I think it is similar. By the way, I tried right now in vra provider version 0.8.6 and I had the same issue.

**Comment by BerryR-RBA** [comment] 2024-02-16 00:34
Yup, I'm having the same issue with v0.8.6.

Suggest that you (and anyone else impacted) upvote #472

**Comment by tenthirtyam** [comment] 2024-07-10 03:26
Duplicate of #472

**Closed by tenthirtyam** 2024-07-10 03:26 UTC
Labels: bug, duplicate, needs-triage
