### ISSUE TITLE
Not able to add further disk storage to vra8. 

### ISSUE THREAD

**Issue by sarveshpat** [vmware/terraform-provider-vra#376] opened 2021-08-26 09:20 UTC
**vRA version**
The vRA Cloud / 8.x version where is issue is found.
**Terraform version**
The terraform version
**terraform-provider-vra plugin version**
The terraform-provider-vra plugin version

**Describe the bug**

**To Reproduce**
1. Terraform config file (for updates, config file before applying the change and the change made)
2. Terraform command
3. Error

**Expected behavior**

**Screenshots**

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
3. crash.log(if any)

**Desktop (please complete the following information):**

**Additional context**

**Comment by frodenas** [comment] 2021-09-09 02:04
@sarveshpat I'm closing this issue as a duplicate of #377.

**Closed by frodenas** 2021-09-09 02:04 UTC
Labels: bug
