### ISSUE TITLE
Creating a resource (by not specifying any deployment ID) doesn't create a new deployment

### ISSUE THREAD

**Issue by pmamtora** [vmware/terraform-provider-vra#121] opened 2019-12-08 02:35 UTC
Provisioning the resource used to create a deployment object with the same name as supplied as resource name but it doesn't create a deployment object anymore. Has this behavior changed?

Here is the main.tf file I am using

provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure      = var.insecure
}

data "vra_project" "this" {
  name        = "e2e-terraform-vra-prithvish"
}

resource "vra_machine" "vms" {
  count = var.instance_count
  description = "terraform vra_machine"
  project_id  = data.vra_project.this.id
  name        = "tf-prithvish-machine"
  image       = "ubuntu"
  flavor      = "small"
  tags {
          key = "foo"
          value = "bar"
  }
  tags {
      key   = "OS"
      value = "Ubuntu"
  }
  timeouts {
        create = "20m"
  }
}

**Comment by Prativa20** [comment] 2019-12-08 02:38
@pmamtora if I understand it correctly, you are saying creating the machine resource is not creating a deployment?

**Comment by pmamtora** [comment] 2019-12-08 02:40
@Prativa20 Yes, that is correct. It is not creating a deployment. Machine is provisioned fine

**Comment by Prativa20** [comment] 2019-12-08 02:43
@pmamtora  Lemme look into it.

**Comment by mdittbrenner215** [comment] 2019-12-08 02:44
It’s using the IaaS api here not deployment.  That is another keyword

**Comment by mdittbrenner215** [comment] 2019-12-08 02:45
You see it under requests not deployments

**Comment by mdittbrenner215** [comment] 2019-12-08 02:50
you want resource "vra_deployment" "this"

**Comment by Prativa20** [comment] 2019-12-08 03:28
Tested it directly through iaas apis. The deployment is not created. This looks like a product issue

**Comment by dmettem** [comment] 2019-12-08 18:50
@pmamtora - Can you please confirm if the issue is on vRA cloud, or on-prem. Also, if the functionality is expected to work in the upcoming vRA product releases, please include that information so that the user community is aware that the functionality may not be readily available to consume yet. Thanks!

**Comment by Prativa20** [comment] 2019-12-08 18:55
@dmettem I debugged this issue with @pmamtora and found out that this is only on on-prem and works fine on vRA cloud. This is related to #120. The on-prem fix for #120 should fix this as well.

**Comment by vrabbi** [comment] 2020-05-03 03:51
this works now in 8.1

**Comment by dmettem** [comment] 2020-05-03 20:17
Thanks @vrabbi for checking! Closing the issue.

**Closed by dmettem** 2020-05-03 20:17 UTC
Labels: vra8-only
