### ISSUE TITLE
Request to add blueprint datasources for blueprint & catalog item

### ISSUE THREAD

**Issue by pmamtora** [vmware/terraform-provider-vra#125] opened 2019-12-09 01:14 UTC
When we provision using vra_deployment resource, we are taking blueprint_id & blueprint _version as input but we will like to use datasource for blueprint the same way we have for vra_project so we can pass the ID and version of blueprint to vra_deployment. We will also need similar datasource for catalog_item too

provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure      = var.insecure
}
data "vra_project" "this" {
  name        = "TF-vRA-Provider Project"
}
resource "vra_deployment" "this" {
  name        = var.deployment_name
  description = "Created for Terraform Demo."
  blueprint_id      = var.blueprint_id
  blueprint_version = var.blueprint_version
  project_id        = data.vra_project.this.id
  inputs = {
    name = "PERMANENT"
  }
  expand_resources = true
  timeouts {
    create = "20m"
  }
}

**Comment by markpeek** [comment] 2019-12-09 01:55
There is a data source for catalog items. Does [this](https://github.com/vmware/terraform-provider-vra/blob/master/examples/deployment/catalog_item/main.tf#L11) usage work for you? Implementation [here](https://github.com/vmware/terraform-provider-vra/blob/master/vra/data_source_catalog_item.go#L1).

**Comment by pmamtora** [comment] 2019-12-09 01:58
Hi @markpeek Thanks for pointing out, this will work for for catalog items

**Comment by mdittbrenner215** [comment] 2019-12-09 14:03
isnt this a duplicate #104

**Comment by dmettem** [comment] 2019-12-09 15:31
Yes. Duplicate of #104.

**Closed by dmettem** 2019-12-09 15:31 UTC
