### ISSUE TITLE
Scaling out causes terraform error

### ISSUE THREAD

**Issue by mdittbrenner215** [vmware/terraform-provider-vra#154] opened 2020-02-12 21:00 UTC
When scaling out VMs terraform errors out as it looks like the completion keyword is different there.

Cloud","inLicense":"rhat"},"dismissed":false,"cancelable":true},"status":"UPDATE_INPROGRESS"}
2020-02-12T14:19:28.400-0500 [DEBUG] plugin.terraform-provider-vra: 2020/02/12 14:19:28 
2020/02/12 14:19:28 [DEBUG] vra_deployment.this: apply errored, but we're indicating that via the Error pointer rather than returning it: deploymentActionStatusRefreshFunc: unknown status COMPLETION
2020/02/12 14:19:28 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/02/12 14:19:28 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/02/12 14:19:28 [TRACE] EvalWriteState: writing current state object for vra_deployment.this
2020/02/12 14:19:28 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/02/12 14:19:28 [TRACE] EvalApplyProvisioners: vra_deployment.this is not freshly-created, so no provisioning is required
2020/02/12 14:19:28 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/02/12 14:19:28 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/02/12 14:19:28 [TRACE] EvalWriteState: writing current state object for vra_deployment.this
2020/02/12 14:19:28 [TRACE] <root>: eval: *terraform.EvalIf
2020/02/12 14:19:28 [TRACE] <root>: eval: *terraform.EvalIf
2020/02/12 14:19:28 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/02/12 14:19:28 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/02/12 14:19:28 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: deploymentActionStatusRefreshFunc: unknown status COMPLETION
2020/02/12 14:19:28 [ERROR] <root>: eval: *terraform.EvalSequence, err: deploymentActionStatusRefreshFunc: unknown status COMPLETION
2020/02/12 14:19:28 [TRACE] [walkApply] Exiting eval tree: vra_deployment.this
2020/02/12 14:19:28 [TRACE] vertex "vra_deployment.this": visit complete
2020/02/12 14:19:28 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/02/12 14:19:28 [TRACE] dag/walk: upstream of "provider.vra (close)" errored, so skipping
2020/02/12 14:19:28 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/02/12 14:19:28 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2020/02/12 14:19:28 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 299
2020/02/12 14:19:28 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate

2020/02/12 14:19:28 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
Error: deploymentActionStatusRefreshFunc: unknown status COMPLETION

It says COMPLETION instead of COMPLETED.

**Comment by mdittbrenner215** [comment] 2020-02-13 19:23
Closed in error this is an issue and was able to reproduce.

**Comment by dmettem** [comment] 2020-03-13 16:51
@mdittbrenner215 Could you please provide the config file before and after that triggered this update and failure?

**Comment by dmettem** [comment] 2020-03-23 23:29
@mdittbrenner215 - Can you please provide more details requested?

**Comment by mdittbrenner215** [comment] 2020-03-24 19:58
Hey Deepak, let me double check and make sure i can reproduce this. Havent done this in awhile.

**Comment by dmettem** [comment] 2020-05-04 20:48
@mdittbrenner215 Do you have an update on this? I'm closing the issue for now. Feel free to reopen if you still see this issue. Also provide the information requested above if you the issue is still seen.

**Closed by dmettem** 2020-05-04 20:48 UTC
Labels: bug, need more info
